name: ci

on:
  push:
    branches:
      - main
      - fix-ci

  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu packages
      run: grep 'sudo apt install' INSTALL | sed 's/\$//' | sh
    - name: Compile
      run: make -C GUI/xephem
    - name: Test
      run: make -C tests

  macos-intel-processor:
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v2
    - name: Install OpenMotif
      run: brew install openmotif && brew info openmotif
    - name: Install OpenSSL
      run: brew install openssl && brew info openssl
    - name: Install XQuartz
      run: brew install xquartz --cask && brew info xquartz
    - name: Install groff
      run: brew install groff && brew info groff
    - name: Compile
      run: make -C GUI/xephem
    - name: Test
      run: make -C tests

  macos-m1-processor:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: Install OpenMotif
      run: brew install openmotif && brew info openmotif
    - name: Install groff
      run: brew install groff && brew info groff
    - name: Install OpenSSL
      run: brew install openssl && brew info openssl
    - name: Install XQuartz
      run: brew install xquartz --cask && brew info xquartz
    - name: Compile
      run: make -C GUI/xephem
    - name: Test
      run: make -C tests
